### ISSUE TITLE
Reusing training infra

### ISSUE THREAD

**Issue by lissyx** [nahuelproietto/deepspeech-spanish-model#7]
Hello,

i've discovered that repo after some contributor reported crashes in https://discourse.mozilla.org/t/segmentation-fault-during-transciption-ds-0-4-1-spanish/53145

I'm happy to see some spanish model, and since it is built usign M-AILABS dataset, I'd suggest you should try and factorize efforts for training to rely on https://github.com/Common-Voice/commonvoice-fr/blob/master/DeepSpeech/Dockerfile.train as italian community did in https://github.com/MozillaItalia/DeepSpeech-Italian-Model

This would allow you to more easily train and release models and stay up-to-date. If you have any issue using the Dockerfile / hackign around it, do not hesitate to ask.

**Comment by nahuelproietto** [comment]
Thanks @lissyx. This repo is no longer maintained. I'll leave a notice about this issue.

**Comment by lyz-code** [comment]
For the missing souls like me, the best resource I've found of deepspeech spanish model right now is [DeepSpeech-Polyglot](https://gitlab.com/Jaco-Assistant/deepspeech-polyglot)
